[package]
name = "app"
version = "0.1.0"
description = "A Tauri App"
authors = ["Mattia Frigiola"]
license = "MIT"
repository = "https://github.com/Sir-Vlad/rilevazioni_sopraluogo_app"
edition = "2024"
rust-version = "1.85.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.0.5", features = [] }

[dependencies]
# Serialization
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }

# Logging
log = "0.4"
tauri-plugin-log = "2.0.0-rc"

# Filesystem
dirs-next = "2.0.0"
tauri-plugin-fs = "2"

# UI and System
tauri = { version = "2.3.1", features = ["devtools", "test"] }
tauri-plugin-dialog = "2"

# Data Processing
polars = { version = "0.46.0", features = ["sql", "lazy"], default-features = false }
calamine = "0.27.0"
rusqlite = { version = "0.35.0", features = ["bundled"] }
itertools = "0.14.0"
rust_xlsxwriter = "0.88.0"

# File Handling
zip = "=2.5.0"

# Error Handling
thiserror = "2.0.12"

# Date and Time
chrono = { version = "0.4.41", default-features = false }

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-single-instance = "2"

[dev-dependencies]
once_cell = "1.21.3"
pretty-sqlite = "0.1.0"
serial_test = "3.2.0"

[package.metadata.bundle.windows]
manifest = "app.manifest"
