[package]
name = "app"
version = "0.1.0"
description = "A Tauri App"
authors = ["Mattia Frigiola"]
license = "MIT"
repository = "https://github.com/Sir-Vlad/rilevazioni_sopraluogo_app"
edition = "2021"
rust-version = "1.85.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.0.5", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
dirs-next = "2.0.0"
tauri = { version = "2.3.1", features = ["devtools"] }
tauri-plugin-log = "2.0.0-rc"
tauri-plugin-dialog = "2"
polars = { version = "0.46.0", features = ["sql", "lazy"] }
calamine = "0.26.1"
rusqlite = { version = "0.35.0", features = ["bundled"] }
itertools = "0.14.0"
rust_xlsxwriter = "0.85.0"
zip = "=2.5.0"
tauri-plugin-fs = "2"

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-single-instance = "2"

[dev-dependencies]
once_cell = "1.21.3"
pretty-sqlite = "0.1.0"
serial_test = "3.2.0"

[package.metadata.bundle.windows]
manifest = "app.manifest"
