version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: app-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: app_development
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    networks:
      - app-network
    command: >
      postgres
      -c logging_collector=off
      -c log_statement=all
      -c log_destination=stderr    
  

  # Opzionale: pgAdmin per gestione GUI
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: app-pgadmin-dev
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - app-network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  app-network:
    driver: bridge