[package]
name = "app_core"
version = "0.1.0"
edition = "2024"

[dependencies]
app_models = {path = "../app_models"}
app_database = {path = "../app_database"}

tauri = {workspace = true}
serde = {workspace = true}
serde_json = {workspace = true}