BEGIN TRANSACTION;
DROP VIEW IF EXISTS V_DATI_STANZE;
DROP VIEW IF EXISTS V_MAT_MIN_EFF_STANZA;
DROP VIEW IF EXISTS V_MQ_INFISSI;
DROP VIEW IF EXISTS V_VET_MIN_EFF_STANZA;

-- modifica di climatizzazione
CREATE TABLE IF NOT EXISTS CLIMATIZZAZIONE_NEW
(
    NOME           TEXT PRIMARY KEY CHECK ( NOME IS NOT NULL AND TRIM(NOME) <> '' ),
    EFF_ENERGETICA INTEGER NOT NULL
);

INSERT INTO CLIMATIZZAZIONE_NEW (NOME, EFF_ENERGETICA)
SELECT CLIMATIZZAZIONE, EFFICIENZA_ENERGETICA
FROM CLIMATIZZAZIONE;

DROP TABLE CLIMATIZZAZIONE;

ALTER TABLE CLIMATIZZAZIONE_NEW
    RENAME TO CLIMATIZZAZIONE;

-- modifica di illuminazione
CREATE TABLE IF NOT EXISTS ILLUMINAZIONE_NEW
(
    LAMPADINA      TEXT PRIMARY KEY CHECK ( LAMPADINA IS NOT NULL AND TRIM(LAMPADINA) <> '' ),
    EFF_ENERGETICA INTEGER NOT NULL
);

INSERT INTO ILLUMINAZIONE_NEW (LAMPADINA, EFF_ENERGETICA)
SELECT LAMPADINA, EFFICIENZA_ENERGETICA
FROM ILLUMINAZIONE;

DROP TABLE ILLUMINAZIONE;

ALTER TABLE ILLUMINAZIONE_NEW
    RENAME TO ILLUMINAZIONE;

-- modifica di materiale infisso
CREATE TABLE IF NOT EXISTS MATERIALE_INFISSO_NEW
(
    MATERIALE      TEXT PRIMARY KEY CHECK ( MATERIALE IS NOT NULL AND TRIM(MATERIALE) <> '' ),
    EFF_ENERGETICA INTEGER NOT NULL
);

INSERT INTO MATERIALE_INFISSO_NEW (MATERIALE, EFF_ENERGETICA)
SELECT MATERIALE, EFFICIENZA_ENERGETICA
FROM MATERIALE_INFISSO;

DROP TABLE MATERIALE_INFISSO;

ALTER TABLE MATERIALE_INFISSO_NEW
    RENAME TO MATERIALE_INFISSO;

-- modifica di vetro infisso
CREATE TABLE IF NOT EXISTS VETRO_INFISSO_NEW
(
    VETRO          TEXT PRIMARY KEY CHECK ( VETRO IS NOT NULL AND TRIM(VETRO) <> '' ),
    EFF_ENERGETICA INTEGER NOT NULL
);

INSERT INTO VETRO_INFISSO_NEW (VETRO, EFF_ENERGETICA)
SELECT VETRO, EFFICIENZA_ENERGETICA
FROM VETRO_INFISSO;

DROP TABLE VETRO_INFISSO;

ALTER TABLE VETRO_INFISSO_NEW
    RENAME TO VETRO_INFISSO;

-- modifica di tipo infisso
CREATE TABLE IF NOT EXISTS TIPO_INFISSO_NEW
(
    NOME TEXT PRIMARY KEY CHECK ( NOME IS NOT NULL AND TRIM(NOME) <> '' )
);

INSERT INTO TIPO_INFISSO_NEW (NOME)
SELECT NOME
FROM TIPO_INFISSO;

DROP TABLE TIPO_INFISSO;

ALTER TABLE TIPO_INFISSO_NEW
    RENAME TO TIPO_INFISSO;

ALTER TABLE STANZA
    RENAME COLUMN CHIAVE TO EDIFICIO_ID;
ALTER TABLE STANZA
    RENAME COLUMN STANZA TO COD_STANZA;

ALTER TABLE INFISSO
    RENAME COLUMN EDIFICIO TO EDIFICIO_ID;

ALTER TABLE STANZA_CON_INFISSI
    RENAME COLUMN ID_INFISSO TO INFISSO_ID;
ALTER TABLE STANZA_CON_INFISSI
    RENAME COLUMN ID_EDIFICIO TO EDIFICIO_ID;
ALTER TABLE STANZA_CON_INFISSI
    RENAME COLUMN ID_STANZA TO STANZA_ID;
ALTER TABLE STANZA_CON_INFISSI
    RENAME COLUMN NUM_INFISSI TO NUM_INFISSO;

ALTER TABLE FOTOVOLTAICO
    RENAME COLUMN ID_EDIFICIO TO EDIFICIO_ID;

ALTER TABLE UTENZE
    RENAME COLUMN ID_EDIFICIO TO EDIFICIO_ID;

ALTER TABLE ANNOTAZIONE_EDIFICIO
    RENAME COLUMN ID_EDIFICIO TO EDIFICIO_ID;

ALTER TABLE ANNOTAZIONE_INFISSO
    RENAME COLUMN ID_INFISSO TO INFISSO_ID;
ALTER TABLE ANNOTAZIONE_INFISSO
    RENAME COLUMN EDIFICIO TO EDIFICIO_ID;

ALTER TABLE ANNOTAZIONE_STANZA
    RENAME COLUMN ID_STANZA TO STANZA_ID;

-- recreating the view with changes
CREATE VIEW V_MAT_MIN_EFF_STANZA AS
SELECT SI.STANZA_ID, MI.MATERIALE
FROM STANZA AS S
         JOIN STANZA_CON_INFISSI AS SI ON S.ID = SI.STANZA_ID
         JOIN INFISSO AS I ON SI.INFISSO_ID = I.ID
         JOIN MATERIALE_INFISSO AS MI ON I.MATERIALE = MI.MATERIALE
WHERE MI.EFF_ENERGETICA IN (
                           SELECT MIN(MI2.EFF_ENERGETICA)
                           FROM STANZA_CON_INFISSI AS SI
                                    JOIN INFISSO AS I2 ON SI.INFISSO_ID = I2.ID
                                    JOIN MATERIALE_INFISSO AS MI2 ON I2.MATERIALE = MI2.MATERIALE
                           WHERE SI.STANZA_ID = S.ID)
GROUP BY SI.STANZA_ID, MI.MATERIALE;

CREATE VIEW V_VET_MIN_EFF_STANZA AS
SELECT SI.STANZA_ID, MI.VETRO
FROM STANZA AS S
         JOIN STANZA_CON_INFISSI AS SI ON S.ID = SI.STANZA_ID
         JOIN INFISSO AS I ON SI.INFISSO_ID = I.ID
         JOIN VETRO_INFISSO AS MI ON I.VETRO = MI.VETRO
WHERE MI.EFF_ENERGETICA IN (
                           SELECT MIN(MI2.EFF_ENERGETICA)
                           FROM STANZA_CON_INFISSI AS SI
                                    JOIN INFISSO AS I2 ON SI.INFISSO_ID = I2.ID
                                    JOIN VETRO_INFISSO AS MI2 ON I2.VETRO = MI2.VETRO
                           WHERE SI.STANZA_ID = S.ID)
GROUP BY SI.STANZA_ID, MI.VETRO;

CREATE VIEW V_MQ_INFISSI AS
SELECT SI.STANZA_ID, SUM(I.MQ * SI.NUM_INFISSO) AS MQ_INFISSI
FROM INFISSO AS I
         JOIN STANZA_CON_INFISSI AS SI ON I.ID = SI.INFISSO_ID
GROUP BY SI.STANZA_ID;

CREATE VIEW V_DATI_STANZE AS
SELECT S.ID,
       E.FASCICOLO,
       S.EDIFICIO_ID AS CHIAVE,
       S.PIANO,
       S.ID_SPAZIO,
       S.COD_STANZA,
       S.DESTINAZIONE_USO,
       S.ALTEZZA,
       S.SPESSORE_MURO,
       S.RISCALDAMENTO,
       S.RAFFRESCAMENTO,
       S.ILLUMINAZIONE,
       COALESCE(ROUND(DGS.MQ_INFISSI, 2), 0) AS MQ_INFISSI,
       DGS.MATERIALE,
       DGS.VETRO
FROM STANZA AS S
         JOIN EDIFICIO AS E ON E.CHIAVE = S.EDIFICIO_ID
    -- AGGIUNGO I DATI DEGLI INFISSI ALLE STANZE CHE C'È LI HANNO
         LEFT JOIN (
                   -- RECUPERO I DATI DELLE STANZE CHE HANNO DEGLI INFISSI
                   SELECT MQ.STANZA_ID, MQ.MQ_INFISSI, M.MATERIALE, V.VETRO
                   FROM V_MQ_INFISSI AS MQ
                            JOIN V_MAT_MIN_EFF_STANZA AS M
                                 ON MQ.STANZA_ID = M.STANZA_ID
                            JOIN V_VET_MIN_EFF_STANZA AS V ON M.STANZA_ID = V.STANZA_ID) AS DGS
                   ON S.ID = DGS.STANZA_ID;

COMMIT;