-- I VALORI NULL RAPPRESENTANO CHE IL DATO NON È DISPONIBILE

PRAGMA FOREIGN_KEYS = ON;

BEGIN TRANSACTION;

-- EDIFICIO TABLE IF NOT EXISTS
CREATE TABLE IF NOT EXISTS EDIFICIO
(
    CHIAVE                TEXT PRIMARY KEY,
    FASCICOLO             TEXT NOT NULL,
    INDIRIZZO             TEXT NOT NULL,
    ANNO_COSTRUZIONE      DATE    DEFAULT NULL,
    ANNO_RIQUALIFICAZIONE DATE    DEFAULT NULL,
    NOTE_RIQUALIFICAZIONE TEXT    DEFAULT NULL,
    ISOLAMENTO_TETTO      BOOLEAN DEFAULT FALSE,
    COMMENTO              TEXT    DEFAULT NULL
);

-- FOTOVOLTAICO TABLE IF NOT EXISTS
CREATE TABLE IF NOT EXISTS FOTOVOLTAICO
(
    ID_EDIFICIO  TEXT PRIMARY KEY REFERENCES EDIFICIO (CHIAVE),
    POTENZA      REAL NOT NULL CHECK ( POTENZA >= 0 ),
    PROPRIETARIO TEXT NOT NULL
);

-- UTENZE TABLE IF NOT EXISTS
CREATE TABLE IF NOT EXISTS UTENZE
(
    ID_EDIFICIO     TEXT PRIMARY KEY REFERENCES EDIFICIO (CHIAVE),
    CT              TEXT DEFAULT NULL CHECK ( LENGTH(CT) = 12),   -- TODO: CHECK PIÙ PRECISI IN RUST
    POD             TEXT DEFAULT NULL CHECK ( LENGTH(POD) = 14 ), -- TODO: CHECK PIÙ PRECISI IN RUST
    INDIRIZZO_POD   TEXT DEFAULT NULL,
    CODICE_ACQUA    TEXT DEFAULT NULL,                            -- TODO: CONTROLLARE SE IL CODICE SIA GIUSTO
    INDIRIZZO_ACQUA TEXT DEFAULT NULL
);

-- STANZA TABLE IF NOT EXISTS
CREATE TABLE IF NOT EXISTS STANZA
(
    ID               INTEGER PRIMARY KEY,
    CHIAVE           TEXT NOT NULL REFERENCES EDIFICIO (CHIAVE),
    PIANO            TEXT    NOT NULL,
    ID_SPAZIO        TEXT    NOT NULL,
    STANZA           TEXT    NOT NULL,
    DESTINAZIONE_USO TEXT    NOT NULL,
    ALTEZZA          INTEGER CHECK ( ALTEZZA >= 0 )       DEFAULT 0,
    SPESSORE_MURO    INTEGER CHECK ( SPESSORE_MURO >= 0 ) DEFAULT 0,
    RISCALDAMENTO    TEXT                                 DEFAULT NULL,
    RAFFRESCAMENTO   TEXT                                 DEFAULT NULL,
    ILLUMINAZIONE    TEXT                                 DEFAULT NULL,
    UNIQUE (CHIAVE, ID_SPAZIO, STANZA, DESTINAZIONE_USO)
);

-- COMMENT_STANZA TABLE IF NOT EXISTS
CREATE TABLE IF NOT EXISTS COMMENT_STANZA
(
    ID      INTEGER PRIMARY KEY REFERENCES STANZA (ID),
    CONTENT TEXT     NOT NULL CHECK ( LENGTH(CONTENT > 0) ),
    DATA    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- INFISSO TABLE IF NOT EXISTS
CREATE TABLE IF NOT EXISTS INFISSO
(
    ID        TEXT PRIMARY KEY,
    ALTEZZA   INTEGER NOT NULL CHECK ( ALTEZZA >= 0 ),
    LARGHEZZA INTEGER NOT NULL CHECK ( LARGHEZZA >= 0 ),
    MATERIALE TEXT    NOT NULL REFERENCES MATERIALE_INFISSO (MATERIALE),
    VETRO     TEXT    NOT NULL REFERENCES VETRO_INFISSO (VETRO),
    MQ        INTEGER GENERATED ALWAYS AS (ALTEZZA * LARGHEZZA) VIRTUAL
);

-- COMMENT_INFISSO TABLE IF NOT EXISTS
CREATE TABLE IF NOT EXISTS COMMENT_INFISSO
(
    ID      TEXT PRIMARY KEY REFERENCES INFISSO (ID),
    CONTENT TEXT     NOT NULL,
    DATA    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- STANZE_CON_INFISSI TABLE IF NOT EXISTS
CREATE TABLE IF NOT EXISTS STANZE_CON_INFISSI
(
    ID_INFISSO TEXT    NOT NULL REFERENCES INFISSO (ID),
    ID_STANZA  INTEGER NOT NULL REFERENCES STANZA (ID),
    PRIMARY KEY (ID_INFISSO, ID_STANZA)
);

-- MATERIALE_INFISSO TABLE IF NOT EXISTS
CREATE TABLE IF NOT EXISTS MATERIALE_INFISSO
(
    ID        INTEGER PRIMARY KEY,
    MATERIALE TEXT NOT NULL UNIQUE
);

-- VETRO_INFISSO TABLE IF NOT EXISTS
CREATE TABLE IF NOT EXISTS VETRO_INFISSO
(
    ID    INTEGER PRIMARY KEY,
    VETRO TEXT NOT NULL UNIQUE
);

-- CLIMATIZZAZIONE TABLE IF NOT EXISTS
CREATE TABLE IF NOT EXISTS CLIMATIZZAZIONE
(
    ID              INTEGER PRIMARY KEY,
    CLIMATIZZAZIONE TEXT NOT NULL UNIQUE
);

-- ILLUMINAZIONE TABLE IF NOT EXISTS
CREATE TABLE IF NOT EXISTS ILLUMINAZIONE
(
    ID        INTEGER PRIMARY KEY,
    LAMPADINA TEXT NOT NULL UNIQUE
);

COMMIT;