DROP VIEW DATI_STANZE;
CREATE VIEW IF NOT EXISTS DATI_STANZE AS
SELECT S.ID, E.FASCICOLO, S.CHIAVE, S.PIANO, S.ID_SPAZIO, S.STANZA, S.DESTINAZIONE_USO,
       S.ALTEZZA, S.SPESSORE_MURO,
       S.RISCALDAMENTO, S.RAFFRESCAMENTO, S.ILLUMINAZIONE, coalesce(DGS.MQ_INFISSI, 0) AS MQ_INFISSI,
       DGS.MATERIALE,
       DGS.VETRO
FROM STANZA AS S
         JOIN EDIFICIO AS E ON E.CHIAVE = S.CHIAVE
    -- Aggiungo i dati degli infissi alle stanze che c'è li hanno
         LEFT JOIN (
                   -- Recupero i dati delle stanze che hanno degli infissi
                   SELECT MQ.ID_STANZA, MQ.MQ_INFISSI, M.MATERIALE, V.VETRO
                   FROM MQ_INFISSI AS MQ
                            JOIN MATERIALE_MENO_EFFICIENTE_STANZA AS M ON MQ.ID_STANZA = M.ID_STANZA
                            JOIN VETRO_MENO_EFFICIENTE_STANZA AS V ON M.ID_STANZA = v.ID_STANZA) AS DGS
                   ON S.ID = DGS.ID_STANZA;
