name: Build Tauri App (Windows)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:


jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install Rust (Stable)
        uses: dtolnay/rust-toolchain@stable

      - name: Install libpq via vcpkg
        run: |
          vcpkg install libpq:x64-windows
          echo "PQ_LIB_DIR=C:\vcpkg\installed\x64-windows\lib" >> $env:GITHUB_ENV
        shell: powershell

      - name: Install frontend dependencies
        run: npm install

      - name: Build Tauri App
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: --bundle msi,nsis
      #        with:
      #          tagName: app-v__VERSION__
      #          releaseName: 'App v__VERSION__'
      #          releaseBody: 'See the assets to download this version and install.'
      #          releaseDraft: true
      #          prerelease: false

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: windows-installers
          path: |
            target/release/bundle/msi/*.msi
            target/release/bundle/nsis/*.exe
          if-no-files-found: warn

